### ISSUE TITLE
UnionLib failed to load server-side

### ISSUE THREAD

**Issue by ChromaPIE** [Stereowalker/Burden-Of-Time#8]
Can't access a direct issue tracker for UnionLib so imma just put it here bc Burden of Time needs it.

I'm no pro but it looks like UnionLib has something thats supposed to be run on client that crashes the server.

<details>
  <summary>Related part in the log</summary>
  
```
[21.09 12:24:10] [Server] [main/ERROR]: Failed to start the minecraft server
[21.09 12:24:10] [Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'unionlib'!
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] Caused byjava.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents in environment type SERVER
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[21.09 12:24:10] [Server] 	at com.stereowalker.unionlib.fabric.PlatformHelper.handleInserts(PlatformHelper.java:60) ~[UnionLib-1.20.1-10.2.0-Fabric.jar:?]
[21.09 12:24:10] [Server] 	at com.stereowalker.unionlib.UnionLib.onModStartup(UnionLib.java:127) ~[UnionLib-1.20.1-10.2.0-Fabric.jar:?]
[21.09 12:24:10] [Server] 	at com.stereowalker.unionlib.fabric.FabricMod.onInitialize(FabricMod.java:25) ~[UnionLib-1.20.1-10.2.0-Fabric.jar:?]
[21.09 12:24:10] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
[21.09 12:24:10] [Server] 	... more
```
</details>

**Comment by ChromaPIE** [comment]
Follow up: The latest update for UnionLib didn't solve the problem but made the crash log a bit different. Here it is: https://mclo.gs/XsbMEAW
